evn: devewrwer
server:
  port: 8766

#自定义负载均衡器
PRODUCT:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
spring: 
  rabbitmq:
    host: 192.168.43.118
    port: 5672
    username: root
    password: sa
management:
  endpoints:
    web:
      exposure:
        include: "*"
zuul:
  routes:
    order:
      path: /orderServer/**
      serverId: order
#      配置空可以获取到cookies
      sensitiveHeaders:

#    简洁写法
#    order: /orderServer/**
#    禁止访问
  ignored-patterns:
    - /orderServer/order/config
